### ISSUE TITLE
图片导致的首行缩进问题

### ISSUE THREAD

**Issue by kirakiseki** [1bitbool/SimplePaper#2]
插入图片后会导致下一段的首行缩进出现问题

有问题的效果
<img width="1249" alt="image" src="https://github.com/1bitbool/SimplePaper/assets/38367158/3b6a56a3-39f3-4c9b-a7c3-b2c1170ab860">

没有问题的正常情况
<img width="1196" alt="image" src="https://github.com/1bitbool/SimplePaper/assets/38367158/d2a62b76-9e37-41db-b163-2abf1af48a31">

参考了[https://github.com/typst/typst/issues/311#issuecomment-1666575619](https://github.com/typst/typst/issues/311#issuecomment-1666575619)后修复了此问题，在figure和image中添加一个高度为0的空段即可
<img width="1221" alt="image" src="https://github.com/1bitbool/SimplePaper/assets/38367158/5e4add87-ca17-4cc5-9614-5680db6c859c">

**Comment by jinhao-huang** [comment]
问题已经修复，感谢 issue。有任何问题欢迎继续反馈。
