### ISSUE TITLE
在problem后使用solution会导致solution无法显示

### ISSUE THREAD

**Issue by handsomexdd1024** [1bitbool/SimplePaper#7]
![image](https://github.com/1bitbool/SimplePaper/assets/36498278/6c31e122-f736-4fa7-bdcc-7493be91bd06)
如上图所示。
我的代码为：
```typst
#import "simplehw.typ": *

#show: project.with(
  title: "运筹学第一次作业",
  authors: (
    (
      name: ""
    ),
  )
)

#show: problem[某一市政建设工程项目在随后的四年中需分别拨款200万元、400万元、800万和500万元，要求拨款在该年年初提供，市政府拟以卖长期公债的方法筹款。长期公债在筹款的四年中市场利息分别预计为9%,8%,8.5%和9.5%,并约定公债利息在工程完工后即开始付息,连续付20年之后还本。在工程建设的头三年,卖公债的多余部分投入银行作为当年有期储蓄,以便用于随后的几年（显然第四年无有期储蓄）,银行的有期储蓄利息率分别预计为8%,7.5%和6.5%。现在的问题是求政府最优的卖公债和有期储蓄方案,使该项市政建设工程得以完成,且付息最低。请为该问题构建线性规划模型。]

#show: solution[#lorem(90)]
```
使用的typst版本为0.10.0, 操作系统为Arch Linux.
不知是不是我的用法有问题？

**Comment by handsomexdd1024** [comment]
同时经过测试，连续使用两个problem或solution也会导致后面的无法显示。

**Comment by handsomexdd1024** [comment]
好的，是我疏忽了（
```typst
#problem[某一市政建设工程项目在随后的四年中需分别拨款200万元、400万元、800万和500万元，要求拨款在该年年初提供，市政府拟以卖长期公债的方法筹款。长期公债在筹款的四年中市场利息分别预计为9%,8%,8.5%和9.5%,并约定公债利息在工程完工后即开始付息,连续付20年之后还本。在工程建设的头三年,卖公债的多余部分投入银行作为当年有期储蓄,以便用于随后的几年（显然第四年无有期储蓄）,银行的有期储蓄利息率分别预计为8%,7.5%和6.5%。现在的问题是求政府最优的卖公债和有期储蓄方案,使该项市政建设工程得以完成,且付息最低。请为该问题构建线性规划模型。]

#solution[#lorem(90)]
```
上面的代码可以产生正确结果。

不过不是很理解为什么（

**Comment by jinhao-huang** [comment]
> 好的，是我疏忽了（
> 
> ```typst
> #problem[某一市政建设工程项目在随后的四年中需分别拨款200万元、400万元、800万和500万元，要求拨款在该年年初提供，市政府拟以卖长期公债的方法筹款。长期公债在筹款的四年中市场利息分别预计为9%,8%,8.5%和9.5%,并约定公债利息在工程完工后即开始付息,连续付20年之后还本。在工程建设的头三年,卖公债的多余部分投入银行作为当年有期储蓄,以便用于随后的几年（显然第四年无有期储蓄）,银行的有期储蓄利息率分别预计为8%,7.5%和6.5%。现在的问题是求政府最优的卖公债和有期储蓄方案,使该项市政建设工程得以完成,且付息最低。请为该问题构建线性规划模型。]
> 
> #solution[#lorem(90)]
> ```
> 
> 上面的代码可以产生正确结果。
> 
> 不过不是很理解为什么（

这个用法是正确的，具体可以参考 Typst 的 [Show Rule](https://typst.app/docs/tutorial/formatting/#show-rules) 和 [Unamed Function](https://typst.app/docs/reference/foundations/function/#unnamed)。

简单来说，Show Rule 是用来重定义元素的，调用函数应该使用 `#` 接函数名

感谢 Issue，之后我会加入一个作业模板的示例
